name: Gorizyon Builder v8

on:
  repository_dispatch:
    types: [aswv_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradelw Yetkisini Düzenle
        run: chmod +x gradlew

      - name: APK Derleme (Build)
        run: ./gradlew assembleDebug
        
      - name: APK Dosyasını Artifact Olarak Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Gorizyon-Build-${{ github.event.client_payload.app_name }}-${{ github.run_id }}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5 # 5 gün boyunca indirilebilir kalır
      
    
